const swaggerAutogen = require("swagger-autogen")();
const outputFile = "./swagger_output.json";
const endpointsFiles = ["./routes/api.routes.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "Ecommerce API", // Updated title to reflect the focus
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module. This API provides endpoints for managing an ecommerce platform.",
  },
  host: "localhost:9090", // Update this if you deploy to a different host
  schemes: ["http"], // Consider adding 'https' if you plan to deploy securely
  consumes: ["application/json"],
  produces: ["application/json"],
  basePath: "/api",
  securityDefinitions: {
    bearerAuth: {
      type: "apiKey",
      name: "Authorization", // Use 'Authorization' as the header name
      scheme: "bearer",
      in: "header",
      description: "Bearer token authentication. Format: 'Bearer <token>'",
    },
  },
  security: { bearerAuth: [] },
};

swaggerAutogen(outputFile, endpointsFiles, doc)
  .then(() => {
    console.log("Swagger documentation generated!");
  })
  .catch((error) => {
    console.error("Error generating Swagger documentation:", error);
  });
